package com.jp.eslocapi.api.entities;

public enum EnumOutrasRendas {
	ALUGUEL_MAQUINAS,
	ALUGUEL_BENFEITORIAS_INSTALACOES,
	ALUGUEL,
	APOSENTADORIA_SERV_PUBLICO,
	APOSENTADORIA_INSS,
	APOSENTADORIA_RURAL,
	ARRENDAMENTO,
	EMPREGO_RURAL,
	EXPLORACAO_MINERAL,
	ROCHAS,
	EMPREGO_URBANO,
	RENDIMENTOS_FINANCEIROS,
	MEACAO,
	OUTRAS_RENDAS,
	RENDAS_NAO_RURAIS,
	VENDA_MAO_DE_OBRA
}
