insert into servico(codigo, descricao, tempo_estimado, valor_estimado) values
('DAPDS', 'DAP - Solicitação de desbloqueio de DAP', '1', '0.00'), 
('GLB', 'Gleba - elaboração de Geo referenciamento', '2', '50.00'), 
('LM', 'Elaboração de limite de crédito para Banco do Brasil', '2', '150.00'), 
('PAAATER', 'PAA - Orientações', '1', '0.00'),
('PNAE', 'PNAE - Elaboração de projeto', '7', '0.00'),
('PNAEATER', 'PNAE - Orientações', '1', '0.00'),
('PAA', 'PAA - Elaboração de projeto', '7', '0.00'),
('AGCAD','Cadastro de uso insignificante', '1', '0.00'), 
('AMIS', 'Interpretação de análise de solo', '1', '0.00'), 
('AMSL', 'Envio de amostra de solo', '10', '25.00'), 
('ATERBOV', 'ATER - Bovinocultura', '1', '0.00'), 
('ATERMA', 'ATER - Meio ambiente', '1', '0.00'), 
('CAD', 'Elaboração de limite de crédito para Sicoob', '2', '150.00'), 
('CAR', 'Cadastro ambiental Rural - Emissão', '2', '200.00'), 
('CAR2V',  'Cadastro ambiental Rural - 2a via', '1', '0.00'), 
('CARRET', 'Cadastro ambiental Rural - Retificação', '2', '200.00'), 
('CRCBBAF', 'Banco do Brasil - Pronaf - Custeio - Elaboração de projeto de crédito rural custeio', '7', '150.00'), 
('CRCBBMP', 'Banco do Brasil - Pronamp - Elaboração de projeto de crédito rural custeio', '7', '150.00'), 
('CRCSBB',  'Banco do Brasil - Elaboração de projeto de crédito rural custeio', '7', '150.00'), 
('CRCSSC',  'Sicoob - Elaboração de projeto de crédito rural custeio', '7', '150.00'), 
('CRIBBAF',  'Banco do Brasil - Pronaf - Elaboração de projeto de crédito rural investimento', '7', '150.00'), 
('CRICBBMP', 'Banco do Brasil - Pronmp - Elaboração de projeto de crédito rural investimento', '7', '150.00'), 
('CRINBB',  'Banco do Brasil - Elaboração de projeto de crédito rural investimento', '7', '150.00'), 
('CRINSC', 'Sicoob - Elaboração de projeto de crédito rural invstimento', '7', '150.00'), 
('CRMABB','Credito Rural Moderagro - Banco do Brasil', '7', '150.00'), 
('DAP', 'DAP - Emissão de Declaração de aptidão ao pronaf', '2', '0.00'), 
('DAPCS',  'DAP - Consulta irregularidade em acesso a DAP', '1', '0.00')
;